# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 14:49
from __future__ import unicode_literals

from django.db import migrations
import programs.apps.programs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_auto_20160318_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='banner_image',
            field=programs.apps.programs.fields.ResizingImageField(blank=True, max_length=1000, null=True, path_template=b'program/banner/{uuid}', sizes=[(1440, 480), (726, 242), (435, 145), (348, 116)], upload_to=b''),
        ),
    ]
